project:
  type: website

website:
  title: "NYT Best Sellers Data"
  navbar:
    title: "NYT Best Sellers Data"
    left:
      - 01-cleaning-hardcover.qmd
      - 02-cleaning-combined.qmd
      - 03-analysis-hardcover.qmd
      - 04-analysis-combined.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    df-print: paged
    
df-print: paged



