name: Update Combined Bestsellers

on:
  schedule:
    - cron: "45 0 * * 4"  # Runs every Thursday at 12:45 AM UTC (7:45 PM EST Wednesday)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R Packages
        uses: actions/cache@v3
        with:
          path: ~/.R/  # Cache location
          key: r-packages-${{ runner.os }}-${{ hashFiles('.github/workflows/*.yml') }}
          restore-keys: |
            r-packages-${{ runner.os }}-

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
            
      - name: Install R Dependencies
        run: |
          R -e 'install.packages(c("readr", "dplyr", "stringr", "lubridate", "rvest"), dependencies=TRUE)'
          R -e 'warnings()'
          
      - name: List Files
        run: ls -R

      - name: Run Combined Scraper
        run: Rscript scripts/update_bestsellers_combined.R  # Ensure this script updates only new data

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data-processed/bestsellers-combined.*
          git commit -m "Updated combined bestsellers list"
          git push
        continue-on-error: true
